### ISSUE TITLE
Add browser type enum value for Edge Chromium 

### ISSUE THREAD

**Issue by ekersale** [wangkanai/Detection#360]
### Is your feature request related to a problem? Please describe.
Does not support Edge Chromium browser.

### Describe the solution you'd like
Add support for this new browser.

**Comment by wangkanai** [comment]
It should, could you help he validate this please.

**Comment by wangkanai** [comment]
Yes, its does by name. But look like the version is not working in Edge Chromium.
![image](https://user-images.githubusercontent.com/10666633/74703341-75bd9f00-523f-11ea-9f69-0c88737d1746.png)

**Comment by thewebchameleon** [comment]
For some weird reason my user agent get interpreted as Safari Mobile

![image](https://user-images.githubusercontent.com/16325369/79688719-6adbb680-8250-11ea-8edf-6d79e931cabc.png)

**Comment by frankhaugen** [comment]
Any movement at all on this? I have tried to use version to get this.

I check if the browser type is edge, if yes, I try to identify if the version is higher than 84, (85 and above uses the chromium engine), and it turns out that it's version is registered as "0", which is definitively. I started tampering with the "GetVersion()", but it's a bit fragile from my perspective.

So version-detection is also FUBAR apparently

**Comment by wangkanai** [comment]
Would like you like join in help me fix the `GetVersion()`? My hand are abit full right now.

**Comment by frankhaugen** [comment]
I did a copypaste of the relevant code in lieu of the nuget, and changed it to replace "edg/" with "edge", before the evaluation of if it contains Browser.Edge, then it worked like a charm. Would you accept such a hack to be introduced?

(I know it's bad form to copypaste library code like it, but I needed the functionality quick, so it's a high priority tech debt item to be resolved the moment a production version of the Nuget is out)

**Comment by frankhaugen** [comment]
@wangkanai I added a PR, (#423 )  as a fix for versions, (see issue #422 that specifically references getting versions).

But on this matter, I've been thinking, and I don't think that there should be "EdgeChromium" alternative, because it will require another "EdgeSomething" if there is another rendering engine change.

Doing something like:
![image](https://user-images.githubusercontent.com/13543585/93716821-14adcf00-fb72-11ea-949f-5acebb3bea57.png)
Isn't too much to ask of users
