### ISSUE TITLE
Blazor support

### ISSUE THREAD

**Issue by ptyll** [wangkanai/Detection#365]
How to detect client in blazor webassembly ?

**Comment by wangkanai** [comment]
That question I don't really know to answer with concept of this library. 

Because Blazor does not have a normal User Agent string sent from the client to server for analyze. What i would imagine is that Blazor would do check its executing environment like what a desktop (console) app does to get the host environment.

**Comment by jdosser** [comment]
That's the problem I've run into. All Microsoft's old libraries used for Browser detection have that function stripped from Core.
And the main reason I need to detect browsers is handling the non-standard Edge and the unsupported IE. 

You can't make this stuff up...

**Comment by wangkanai** [comment]
@jdosser Good point you have made there. 

For me, I think its just a matter of time when such feature or library would be available. Similar to how I get started with this project for ASP.NET Core because I need to the feature and Microsoft did not provided for me. So I created it myself.

While, I'm interested in the request feature. But for the time being I'm still busy with other projects.

**Comment by wangkanai** [comment]
Its look like we have support for Blazor Server Side web application now 😺

**Comment by wangkanai** [comment]
Blazor Server Side feature added
