### ISSUE TITLE
Trouble with examples.

### ISSUE THREAD

**Issue by jdosser** [wangkanai/Detection#367]
### Describe the bug
I'm trying to get ANY kind of browser recognition within the @code block of a Blazor project.
So, I'm following your example and the first issue is this instruction: Adding the TagHelper features to your web application with the following in your _ViewImports.cshtml.

I don't see a ViewImports.cshtml file in Blazor. So do I put these files elsewhere? I'm not sure.

Next issue:
I tried implementing the Razor example for pages 'without PageModel.' When I tried inserting your code, I received the error: The name 'ViewData' does not exist in the current context.

And finally, a little later, you provide an example of dependency injection using IndexModel. My problem is I don't know anything about MVC so an MVC example isn't much help. More helpful would be not only an example of the class but how it's called.
### To Reproduce
I'm not sure. I loaded Studio 2019, loaded a default project and set to work plugging in you example. I hit an error at 'ViewData' and got no further.

**Comment by wangkanai** [comment]
I'm not sure what are you to do, but what i'm trying understand from reading your clarification is that you are trying to develop a Blazor project. While this library was made for server-side ASP.Net Core web application (MVC and Razor Page).

Blazor Server-side and Blazor WebAssembly is not a support feature in `Wangkanai.Detection` as of yet in 3.0 milestone. Maybe I will into Blazor later in the future. #365 Blazor has a different working mind-shift to work with, because It not your typical web application using HTTP GET request.

**Comment by jdosser** [comment]
Thanks so much Sarin for the response, and all your work on this.
Yes, it IS a server Side Blazor project.
You'd think Microsoft would provide a method for recognizing browsers since
IE 11 doesn't even run Blazor and you need to recognize that.
What was Microsoft thinking?

Stay healthy and have a great weekend,

Jeff

________________________________

**Comment by wangkanai** [comment]
@jdosser Thank you very much for your kind words.

For Blazor working with this library, I will put it a backlog tracking with #365.

Stay safe from CCP virus and stay healthy.
